// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import * as dotenv from 'dotenv';
import { defineConfig } from "prisma/config";
dotenv.config();

export default defineConfig({
  schema: "prisma/models",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});