name: Fullstack CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------
      # FRONTEND BUILD
      # -------------------------
      - name: Setup Node (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      # -------------------------
      # BACKEND BUILD
      # -------------------------
      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Generate Prisma Client
        working-directory: backend
        run: npx prisma generate
  
      - name: Build Backend
        working-directory: backend
        run: npm run build
